# This file was generated by Appraisal

source "https://rubygems.org"

gem "spree", ' ~> 3.4.0'
gem "spree_auth_devise", github: "spree/spree_auth_devise", branch: "master"
gem "rails_test_params_backport", group: :test

gemspec
